name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gitlab-portainer-deploy:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitlab-portainer-deploy:latest